version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - room-app-network
  room-service:
    build: ./room-service
    depends_on: 
      - rabbitmq
      - db-room
    restart: on-failure:always
    networks:
      - room-app-network
    ports:
      - 8082:8082
  user-service:
    build: ./user-service
    ports:
      - 8081:8081
    depends_on: 
      - rabbitmq
      - db-user
    restart: on-failure:always
    networks:
      - room-app-network
  db-room:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db-room:/var/lib/postgresql/data
    networks:
      - room-app-network
  db-user:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes: 
      - db-user:/var/lib/postgresql/data
    networks:
      - room-app-network
networks:
  room-app-network:
    driver: bridge
volumes:
  db-user:
    driver: local
  db-room:
    driver: local